package rooms;

public enum RoomName {
	GARDENS, ORGANROOM, DININGROOM, ENTRANCEHALL, FOYER, GRANDSTAIRCASE, JUNKROOM, BASEMENTLANDING, CATACOMBS, CHASM, PENTAGRAMCHAMBER, CREAKYHALLWAY,
	SERVANTSQUARTERS, MASTERBEDROOM, BEDROOM, UNDERGROUNDLAKE, STATUARYCORRIDOR, STOREROOM, DUSTYHALLWAY, BLOODYROOM, WINECELLAR, VAULT, UPPERLANDING,
	GRAVEYARD, PATIO, TOWER, BALCONY, GALLERY, BALLROOM, STAIRSFROMBASEMENT, ATTIC, GAMEROOM, CONSERVATORY, CHARREDROOM, ABANDONEDROOM, KITCHEN,
	RESEARCHLABORATORY, OPERATINGLABORATORY, CHAPEL, GYMNASIUM, LARDER, LIBRARY, CRYPT, FURNACEROOM
}
