package rooms;

public enum RoomName {
	GARDENS, ORGANROOM, DININGROOM, ENTRANCEHALL, FOYER, GRANDSTAIRCASE, JUNKROOM, BASEMENTLANDING, CATACOMBS, CHASM, PENTAGRAMCHAMBER, CREAKYHALLWAY,
	SERVANTSQUARTERS, MASTERBEDROOM, BEDROOM, UNDERGROUNDLAKE, STATUARYCORRIDOR, STOREROOM, DUSTYHALLWAY, BLOODYROOM, WINECELLAR, VAULT, UPPERLANDING
}
